name: Run Pydmr Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', '3.7', '3.8', '3.9' ]
    name: ubuntu-latest Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip3 install -U requests
      - name: Run tests with python3
        run: python3 -m unittest
